
services:
  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
    image: gpanico_keycloak
    restart: always
    ports:
      - "8080:8081"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8000:8080"


volumes:
  postgres:
    name: "postgres"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/data/postgres"
