# GENERAL INFO
server:
  port: 4242
spring:
  application:
    name: demo
# SPRING SECURITY
  security:
    user:
      name: admin
      password: admin
# OAUTH2 RESOURCE SERVER
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_PROTOCOL:http}://${KEYCLOAK_DOMAIN:localhost}:${KEYCLOAK_PORT:8081}/realms/${KEYCLOAK_REALM:Demo}
